type SpeakerInfo = {
  name: string;
  year: string;
  title?: string;
  url: string;
};

export default defineEventHandler((): SpeakerInfo[] => {
  return [
    {
      name: "Evan You",
      year: "2018",
      title: "Vue 3.0 Updates",
      url: "https://vuefes.jp/2018/speakers/yyx990803/",
    },
    {
      name: "Sarah Drasner",
      year: "2018",
      title: "Next-level Vue Animations",
      url: "https://vuefes.jp/2018/speakers/sdras/",
    },
    {
      name: "Takanori Oki",
      year: "2018",
      title: "Vue.js と Web Components のこれから",
      url: "https://vuefes.jp/2018/speakers/takanorip/",
    },
    {
      name: "katashin",
      year: "2018",
      title: "Vue Designer: デザインと実装の統合",
      url: "https://vuefes.jp/2018/speakers/ktsn/",
    },
    {
      name: "Edd Yerburgh",
      year: "2018",
      title: "Unit testing a Vuex store",
      url: "https://vuefes.jp/2018/speakers/eddyerburgh/",
    },
    {
      name: "菅原 孝則",
      year: "2018",
      title: "Atomic Design のデザインと実装の狭間",
      url: "https://vuefes.jp/2018/speakers/ts020/",
    },
    {
      name: "Sébastien Chopin",
        year: "2018",
        title: "Nuxt.js 2.0",
        url: "https://vuefes.jp/2018/speakers/Atinux/",
    },
    {
        name: "Rahul Kadyan",
        year: "2018",
        title: "A deep dive in SFC compilation",
        url: "https://vuefes.jp/2018/speakers/znck/",
    },
    {
        name: "福井 烈",
        year: "2018",
        title: "note のフロントエンドを Nuxt.js で再構築した話",
        url: "https://vuefes.jp/2018/speakers/fukuiretu/",
    },
    {
        name: "Guillaume Chau",
        year: "2018",
        title: "Vue CLI 3 and its Graphical User Interface",
        url: "https://vuefes.jp/2018/speakers/Akryum/",
    },
    {
        name: "土屋 和良",
        year: "2018",
        title: "1年間単体テストを書き続けた現場から送る Vue Component のテスト",
        url: "https://vuefes.jp/2018/speakers/tsuchikazu/",
    },
    {
        name: "Evan You",
        year: "2019",
        title: "Keynote",
        url: "https://vuefes.jp/2019/sessions/yyx990803/",
    },
    {
        name: "Alexandre Chopin",
        year: "2019",
        title: "What's Nuxt?",
        url: "https://vuefes.jp/2019/sessions/alexchopin/",
    },
    {
        name: "Sébastien Chopin",
        year: "2019",
        title: "Introduction to Nuxt 3",
        url: "https://vuefes.jp/2019/sessions/Atinux/",
    },
    {
        name: "沼田 佳介",
        year: "2019",
        title: "アンチパターンから学ぶ Atomic Design with Vue.js",
        url: "https://vuefes.jp/2019/sessions/keinuma/",
    },
    {
        name: "黒川 智",
        year: "2019",
        title: "“何もない” を作る、コンポーネント指向な余白設計",
        url: "https://vuefes.jp/2019/sessions/blackawa/",
    },
    {
        name: "浅野 慧",
        year: "2019",
        title: "Vue CLI、GraphQL を用いた一休.com レストラン管理画面のリニューアル",
        url: "https://vuefes.jp/2019/sessions/ninjinkun/",
    },
    {
        name: "Chris Fritz",
        year: "2019",
        title: "Enterprise Vue: Patterns That Scale",
        url: "https://vuefes.jp/2019/sessions/chrisvfritz/",
    },
    {
        name: "高瀬 悠磨",
        year: "2019",
        title: "4000万人が使うサービスを jQuery から Nuxt.js にまで置き換えていった話",
        url: "https://vuefes.jp/2019/sessions/retty-y-takase/",
    },
    {
        name: "大山 奥人",
        year: "2019",
        title: "Vue.js meets Web Accessibility",
        url: "https://vuefes.jp/2019/sessions/yamanoku/",
    },
    {
        name: "石岡 将明",
        year: "2019",
        title: "Nuxt.js + TypeScript で 01 開発",
        url: "https://vuefes.jp/2019/sessions/masaakikunsan/",
    },
    {
        name: "Jen Looper",
        year: "2019",
        title: "WineUp: Machine Learning, Mobile Apps, Wine, Cheese, and You",
        url: "https://vuefes.jp/2019/sessions/jlooper/",
    },
    {
        name: "甲斐 啓真",
        year: "2019",
        title: "次世代のデザインとフロントエンド開発の GUI 化",
        url: "https://vuefes.jp/2019/sessions/keimakai/",
    },
    {
        name: "手島 拓也",
        year: "2019",
        title: "とある Nuxt.js 案件の本当にあった怖い話。",
        url: "https://vuefes.jp/2019/sessions/tejitak/",
    },
    {
        name: "宇野 航平",
        year: "2019",
        title: "型がある楽しさとつらさ",
        url: "https://vuefes.jp/2019/sessions/konu96/",
    },
    {
        name: "ULIVZ",
        year: "2019",
        title: "The Present and Future about VuePress",
        url: "https://vuefes.jp/2019/sessions/ulivz/",
    },
    {
        name: "Pine Wu",
        year: "2019",
        title: "Vue Tooling について語るときに僕の語ること",
        url: "https://vuefes.jp/2019/sessions/octref/",
    },
    {
        name: "吉井 健文",
        year: "2019",
        title: "TypeScript CompilerAPI で挑む Vuex の型推論",
        url: "https://vuefes.jp/2019/sessions/takefumi-yoshii/",
    },
    {
        name: "Evan You",
        year: "2022",
        title: "キーノート",
        url: "https://vuefes.jp/2022/sessions/yyx990803",
    },
    {
        name: "小林 和弘",
        year: "2022",
        title: "メドピアのサービスにおけるテスト戦略の過去と未来",
        url: "https://vuefes.jp/2022/sponsor-sessions/medpeer",
    },
    {
        name: "星 賢一, 岸本 卓也",
        year: "2022",
        title: "業務システムでVue.jsを活用するための取り組み",
        url: "https://vuefes.jp/2022/sponsor-sessions/future",
    },
    {
        name: "芳賀 将至",
        year: "2022",
        title: "Design System Meets Vue.js",
        url: "https://vuefes.jp/2022/sponsor-sessions/cloudsign",
    },
    {
        name: "m0nch1",
        year: "2022",
        title: "プロダクト開発を止めずに Composition API と TypeScript に最速で移行するための戦い",
        url: "https://vuefes.jp/2022/sponsor-sessions/stores",
    },
    {
        name: "柴坂浩行",
        year: "2022",
        title: "LINE MUSIC のパフォーマンスを向上させた Vue3 マイグレーション",
        url: "https://vuefes.jp/2022/sponsor-sessions/line",
    },
    {
        name: "竹内 秀行",
        year: "2022",
        title: "WebSockets with Vue.js",
        url: "https://vuefes.jp/2022/sponsor-sessions/yesod",
    },
    {
        name: "福井 潤之（フクイ ヒロユキ）",
        year: "2022",
        title: "Vue.jsのUIを強化するグレープシティのJavaScriptライブラリ",
        url: "https://vuefes.jp/2022/sponsor-sessions/grapecity",
    },
    {
        name: "荻野 淳也, Shoko",
        year: "2022",
        title: "急拡大中のヘルステックSaaSを支えるフロントエンド開発",
        url: "https://vuefes.jp/2022/sponsor-sessions/icare",
    },
    {
        name: "がっちゃん",
        year: "2022",
        title: "BASEのフロントエンド組織の人数が2.5倍になって起きた変化",
        url: "https://vuefes.jp/2022/sponsor-sessions/base",
    },
    {
        name: "とよへい",
        year: "2022",
        title: "負債が溜まったレガシーフロントエンド画面を Vue.js でリプレイスした話",
        url: "https://vuefes.jp/2022/sessions/t0yohei",
    },
    {
        name: "腹筋ローラーの力を信じろ",
        year: "2022",
        title: "不確実性のある将来に対応するためのデザイン戦略",
        url: "https://vuefes.jp/2022/sessions/8845musign",
    },
    {
        name: "miyaoka",
        year: "2022",
        title: "Vue2 Vue3 マイグレーション 令和最新 最強",
        url: "https://vuefes.jp/2022/sessions/miyaoka",
    },
    {
        name: "oreo",
        year: "2022",
        title: "レガシーなMPAアプリケーションをwebpackからviteに移行する話",
        url: "https://vuefes.jp/2022/sessions/oreo",
    },
    {
        name: "ebiryu",
        year: "2022",
        title: "provide/injectを用いたローカルな状態管理",
        url: "https://vuefes.jp/2022/sessions/ebiryu",
    },
    {
        name: "掛水優輝",
        year: "2022",
        title: "Nuxt2 + Composition API から Nuxt Bridge へのマイグレーションのすゝめ",
        url: "https://vuefes.jp/2022/sessions/l4dybird",
    },
    {
        name: "古澤 棟熏",
        year: "2022",
        title: "ブログを作るならNuxt Content v2はいいぞ",
        url: "https://vuefes.jp/2022/sessions/FurusawaKaoru",
    },
    {
        name: "やまのく",
        year: "2022",
        title: "Vue.js でアクセシブルなコンポーネントをつくるために",
        url: "https://vuefes.jp/2022/sessions/yamanoku",
    },
    {
        name: "川野邉 賢二",
        year: "2022",
        title: "「こわくない」Vuetifyで始めるOSSコントリビュート",
        url: "https://vuefes.jp/2022/sessions/kenji7157",
    },
    {
        name: "志賀 奎太",
        year: "2022",
        title: "施策を止めるな！Vue2からVue3への移行",
        url: "https://vuefes.jp/2022/sessions/shigasy",
    },
    {
        name: "tbashiyy",
        year: "2022",
        title: "十数万レコードに耐えうるVue.jsプロジェクトを実現するためのパフォーマンスチューニング",
        url: "https://vuefes.jp/2022/sessions/tbashiyy",
    },
    {
        name: "川俣 涼",
        year: "2022",
        title: "JSからTSへ移行したVue.jsプロダクトの型チェックを漸進的に強化する",
        url: "https://vuefes.jp/2022/sessions/kawamataryo",
    },
    {
        name: "Guillaume Chau",
        year: "2022",
        title: "How Vite enables Histoire",
        url: "https://vuefes.jp/2022/sessions/Akryum",
    },
    {
        name: "田中弘治",
        year: "2022",
        title: "Nuxt モジュールの作り方を知って 開発した機能を再利用しよう",
        url: "https://vuefes.jp/2022/sessions/monsat",
    },
    {
        name: "太田 洋介",
        year: "2022",
        title: "eslint-plugin-vueを使用して継続的にVue3移行する",
        url: "https://vuefes.jp/2022/sessions/ota-meshi",
    },
    {
        name: "Eduardo San Martin Morote",
        year: "2022",
        title: "State Alchemy with Pinia",
        url: "https://vuefes.jp/2022/sessions/posva",
    },
    {
        name: "watsuyo",
        year: "2022",
        title: "安全に開発効率を上げるための Vue 2.7 移行",
        url: "https://vuefes.jp/2022/sessions/watsuyo",
    },
    {
        name: "Sébastien Chopin",
        year: "2022",
        title: "From Zero to One",
        url: "https://vuefes.jp/2022/sessions/Atinux",
    },
    {
        name: "Matias Capeletto",
        year: "2022",
        title: "Vite 3 and Beyond",
        url: "https://vuefes.jp/2022/sessions/patak",
    },
    {
        name: "菅家 大地",
        year: "2022",
        title: "NuxtJSによるJamstack構築とNuxt 3でどう変わるのか",
        url: "https://vuefes.jp/2022/sessions/KanDai",
    },
    {
        name: "Jessica Sachs",
        year: "2022",
        title: "Component Testing",
        url: "https://vuefes.jp/2022/sessions/Jess",
    },
    {
        name: "みゅーとん",
        year: "2022",
        title: "デザインシステムを後から導入する前提で作った 変更に強いNuxt3プロジェクトの構成",
        url: "https://vuefes.jp/2022/sessions/mew-ton",
    },
    {
        name: "プログラミングをするパンダ",
        year: "2022",
        title: "共通コンポーネントのテスト実装方法にあえてVRTを選択した話",
        url: "https://vuefes.jp/2022/sessions/KushibikiMashu",
    },
    {
        name: "Anthony Fu",
        year: "2022",
        title: "Patterns of VueUse",
        url: "https://vuefes.jp/2022/sessions/anfu",
    },
    {
        name: "Evan You",
        year: "2023",
        title: "キーノート",
        url: "https://vuefes.jp/2023/sessions/yyx990803",
    },
    {
        name: "篠田 貴大",
        year: "2023",
        title: "走りながらエンジンを交換する 〜 大規模プロダクトを成長させつつVue 3にするには 〜",
        url: "https://vuefes.jp/2023/sponsor-sessions/cloudsign",
    },
    {
        name: "山本 一将",
        year: "2023",
        title: "社内UIコンポーネントライブラリがエンジニアチームにもたらした本当の価値",
        url: "https://vuefes.jp/2023/sponsor-sessions/unique-vision",
    },
    {
        name: "鵜木 義秀",
        year: "2023",
        title: "Vue.jsを活用して開発リードタイムが1/3になった話",
        url: "https://vuefes.jp/2023/sponsor-sessions/link-and-motivation-group",
    },
    {
        name: "藤村 大介, wattanx (ワッタン)",
       year: "2023",
        title: "「Youはなぜコントリビュータに？」論より動くもの.fm 出張版",
        url: "https://vuefes.jp/2023/sponsor-sessions/stores",
    },
    {
        name: "安積 洋",
        year: "2023",
        title: "Vue.jsプロジェクト設計のベストプラクティスを求めて",
        url: "https://vuefes.jp/2023/sponsor-sessions/mntsq",
    },
    {
        name: "小林 和弘",
        year: "2023",
        title: "Vue 2のEOLまで二ヶ月ですが進捗どうですか？",
        url: "https://vuefes.jp/2023/sponsor-sessions/medpeer",
    },
    {
        name: "野崎 才門",
        year: "2023",
        title: "Nuxt 3ではじめるテスト導入戦略と初手",
        url: "https://vuefes.jp/2023/sponsor-sessions/hacomono",
    },
    {
        name: "みゅーとん (mew-ton)",
        year: "2023",
        title: "Nuxt 2から3へマイグレーションする方法考えてたら、マイクロフロントエンドのフレームワークができた話",
        url: "https://vuefes.jp/2023/sessions/mew-ton",
    },
    {
        name: "市原 雄太",
        year: "2023",
        title: "OpenAI APIをNuxt.jsに入れてみた的な話",
        url: "https://vuefes.jp/2023/sponsor-sessions/coconala",
    },
    {
        name: "Sebastien Chopin",
        year: "2023",
        title: "Nuxt to the Edge",
        url: "https://vuefes.jp/2023/sessions/atinux",
    },
    {
        name: "t0yohei (トヨヘイ)",
       year: "2023",
        title: "Vueを使ってGrid Systemを実装した話",
        url: "https://vuefes.jp/2023/sessions/t0yohei",
    },
    {
        name: "楢山 哲弘",
        year: "2023",
        title: "WebGISとVue.jsの親和性について",
        url: "https://vuefes.jp/2023/sessions/northprint",
    },
    {
        name: "きらぷか (kira-puka)",
        year: "2023",
        title: "Nuxt3のモジュール開発は意外と簡単？ Module Author Guideをのぞいてみよう",
        url: "https://vuefes.jp/2023/sessions/kira-puka",
    },
    {
        name: "0yu (オユ)",
     year: "2023",
        title: "Vue 3/Electronで自作したマークダウンエディタをVue 3/Tauriにリプレイスした話",
        url: "https://vuefes.jp/2023/sessions/yud0uhu",
    },
    {
        name: "やまのく",
        year: "2023",
        title: "画面遷移から考えるNuxtアプリケーションをアクセシブルにする方法",
        url: "https://vuefes.jp/2023/sessions/yamanoku",
    },
    {
        name: 'Daniel Roe',
        year: '2023',
        title: 'Nuxt Core Team Member',
        url: 'https://vuefes.jp/2023/sessions/daniel-roe',
    },
    {
        name: "山下 裕一朗 (Yuichiro Yamashita)",
        year: "2023",
        title: "18営業日で350コンポーネント規模のVueアプリにデザインシステムを導入する方法",
        url: "https://vuefes.jp/2023/sessions/baseballyama",
    },
    {
        name: "まぁし（知念）",
        year: "2023",
        title: "Nuxt 3でJamstackテンプレートを作るときの考え方",
        url: "https://vuefes.jp/2023/sessions/chocodogmagic",
    },
    {
        name: "Anthony Fu",
        year: "2023",
        title: "Anthony's Roads to Open Source - The Set Theory",
        url: "https://vuefes.jp/2023/sessions/antfu",
    },
    {
        name: "wattanx (ワッタン)",
       year: "2023",
        title: "Demystifying Nuxt Bridge 〜 あなたがまだ見ぬ可能性とその活用法 〜",
        url: "https://vuefes.jp/2023/sessions/wattanx",
    },
    {
        name: "mizdra (ミズドラ)",
       year: "2023",
        title: "Vue Language Serverから生まれたVolar.jsと、それが秘める可能性",
        url: "https://vuefes.jp/2023/sessions/mizdra",
    },
    {
        name: "Matias Capeletto",
        year: "2023",
        title: "Vite: Stories of collaboration",
        url: "https://vuefes.jp/2023/sessions/patak-dev",
    },
    {
        name: "Nozomu Ikuta",
        year: "2023",
        title: "Deep Dive to UnJS and Nuxt 3",
        url: "https://vuefes.jp/2023/sessions/nozomu-ikuta",
    },
    {
        name: "53able (ゴー)",
     year: "2023",
        title: "SOLID原則に基づくSFC実装",
        url: "https://vuefes.jp/2023/sessions/53able",
    },
    {
        name: "fuqda (フクダ)",
      year: "2023",
        title: "Composition API時代のPub/Subパターンでの状態管理",
        url: "https://vuefes.jp/2023/sessions/fuqda",
    },
    {
        name: "Hieu (グエンゴックヒエウ)",
        year: "2023",
        title: "Exploring the Power of Error Handling in Vue JS",
        url: "https://vuefes.jp/2023/sessions/hieu",
    },
    {
        name: "湧川 仁貴",
        year: "2023",
        title: "フルスクラッチECの基盤であるNuxt 2を3に移行し、開発の効率性とパフォーマンスを高める",
        url: "https://vuefes.jp/2023/sessions/hitoki-wakugawa",
    },
    {
        name: "Harlan Wilton",
        year: "2023",
        title: "Getting your head around your <head>",
        url: "https://vuefes.jp/2023/sessions/harlan-zw",
    },
    {
        name: "翠 (sapphi-red)",
        year: "2023",
        title: "マルチスレッドフレンドリーなJavaScriptを求めて",
        url: "https://vuefes.jp/2023/sessions/sapphi-red",
    },
    {
        name: "sorami (ソラミ)",
        year: "2023",
        title: "Vue.jsと3D可視化 - 産総研のOSS「AIST 3DDB Client」を例に",
        url: "https://vuefes.jp/2023/sessions/sorami",
    },
    {
        name: "太田 洋介 (ota-meshi)",
        year: "2023",
        title: "eslint-plugin-vueの現状と今後",
        url: "https://vuefes.jp/2023/sessions/ota-meshi",
    },
    {
        name: "甲斐 啓真 (Keima)",
        year: "2023",
        title: "STUDIOの作り方 2023 ver.",
        url: "https://vuefes.jp/2023/sessions/keima",
    },
    {
        name: "尾形 将平",
        year: "2023",
        title: "「defineCustomElement」を活用したサービス共通のUIコンポーネントライブラリ",
        url: "https://vuefes.jp/2023/sponsor-sessions/gmo-internet-group",
    },
    {
        name: "Evan You",
        year: "2024",
        title: "キーノート",
        url: "https://vuefes.jp/2024/sessions/yyx990803",
    },
    {
        name: "Boshen Chen",
        year: "2024",
        title: "Oxc - The JavaScript Oxidation Compiler",
        url: "https://vuefes.jp/2024/sessions/boshen",
    },
    {
        name: "田中 陽",
        year: "2024",
        title: "同期する都市のキャンバス：Vue.jsによる大規模メディアインスタレーションの舞台裏",
        url: "https://vuefes.jp/2024/sessions/you-tanaka",
    },
    {
        name: "こん",
        year: "2024",
        title: "普通のエンジニアが頑張って30万行のNuxt3バージョンアップした話",
        url: "https://vuefes.jp/2024/sessions/k0n_karin",
    },
    {
        name: "Pooya Parsa",
        year: "2024",
        url: "https://vuefes.jp/2024/sessions/pi0",
    },
    {
        name: "山下 裕一朗",
        year: "2024",
        title: "Vue 3 と Svelte 5 のランタイムを比較する 〜技術を一段深く理解する〜",
        url: "https://vuefes.jp/2024/sessions/baseballyama",
    },
    {
        name: "Kazuki Shimamoto",
        year: "2024",
        title: "Vaporモードを大規模サービスに最速導入して学びを共有する",
        url: "https://vuefes.jp/2024/sessions/kz_shimamo",
    },
    {
        name: "Alexander Lichter",
        year: "2024",
        title: "Gems of Nuxt: 8 Features Every Nuxt Developer Should Know!",
        url: "https://vuefes.jp/2024/sessions/alexander-lichter",
    },
    {
        name: "いがにん",
        year: "2024",
        title: "Vue.js、Nuxtの機能を使い、大量のコピペコードをリファクタリングする",
        url: "https://vuefes.jp/2024/sessions/igayamaguchi",
    },
    {
        name: "Eduardo San Martin Morote",
        year: "2024",
        title: "Async State Management with Vue Router",
        url: "https://vuefes.jp/2024/sessions/eduardo-san-martin-morote",
    },
    {
        name: "まぁし",
        year: "2024",
        title: "2万ページのSSG運用における工夫と注意点",
        url: "https://vuefes.jp/2024/sessions/chocodogmagic",
    },
    {
        name: "大橋一真",
        year: "2024",
        title: "Trusted Types APIとVue.js",
        url: "https://vuefes.jp/2024/sessions/kazumaohashi",
    },
    {
        name: "ツノ",
        year: "2024",
        title: "v-modelの歩みを振り返る",
        url: "https://vuefes.jp/2024/sessions/tsuno",
    },
    {
        name: "tsukkee",
        year: "2024",
        title: "Vue SFCのtemplateでTypeScriptの型を活用しよう",
        url: "https://vuefes.jp/2024/sessions/tsukkee",
    },
    {
        name: "Rachel",
        year: "2024",
        title: "Nuxtで段階的レンダリングを活用してUXを最大化するためのTips",
        url: "https://vuefes.jp/2024/sessions/rachel_camper",
    },
    {
        name: "Nozomu Ikuta",
        year: "2024",
        title: "Demystifying Vite Internals",
        url: "https://vuefes.jp/2024/sessions/nozomu-ikuta",
    },
    {
        name: "odan",
        year: "2024",
        title: "Vitest Browser Mode への期待",
        url: "https://vuefes.jp/2024/sessions/odan3240",
    },
    {
        name: "tokuda109",
        year: "2024",
        title: "Protocol BuffersとNuxt3で開発生産性を上げるためのスキーマファースト開発の紹介",
        url: "https://vuefes.jp/2024/sessions/tokuda109",
    },
    {
        name: "Yutaro Koizumi",
        year: "2024",
        title: "Nuxt × Vue Router の力を最大限を引き出す機能を紹介 ～Typed Pages, Nested Routes, Routes' Matching Syntax～",
        url: "https://vuefes.jp/2024/sessions/ykoizumi0903",
    },
    {
        name: "satoki",
        year: "2024",
        title: "Vue.jsプロジェクトに出てくるeslintと仲良くなる",
        url: "https://vuefes.jp/2024/sessions/satoki_1226",
    },
    {
        name: "Kevin Deng",
        year: "2024",
        url: "https://vuefes.jp/2024/sessions/kevin",
    },
    {
        name: "Hal",
        year: "2024",
        title: "Vue3の一歩踏み込んだパフォーマンスチューニング 2024",
        url: "https://vuefes.jp/2024/sessions/hal",
    },
    {
        name: "wattanx",
        year: "2024",
        title: "Deep dive into Nuxt Server Components",
        url: "https://vuefes.jp/2024/sessions/wattanx",
    },
    {
        name: "Anthony Fu",
        year: "2024",
        title: "Anthony's Road to Open Source - Yak Shaving",
        url: "https://vuefes.jp/2024/sessions/antfu",
    },
    {
        name: "GANGAN",
        year: "2024",
        title: "Nuxt UI Pro、NuxtHub、Nuxt Scripts、Nuxtエコシステムをふんだんに利用して開発するコーポレートサイト",
        url: "https://vuefes.jp/2024/sessions/gangan_nikki",
    }
  ];
});
