catalogs:
  cloudflare:
    '@nuxthub/core': 0.9.1
    wrangler: 4.51.0
  css:
    tailwindcss: 4.1.17
  icon:
    '@iconify-json/heroicons-solid': 1.2.1
    '@iconify-json/lucide': 1.2.76
  nuxt:
    '@nuxt/ui': 4.2.1
    nuxt: 4.2.1
  test:
    '@nuxt/eslint': 1.11.0
    '@nuxt/eslint-config': 1.11.0
    '@nuxt/test-utils': 3.20.1
    '@vue/test-utils': 2.4.6
    eslint: 9.39.1
    happy-dom: 20.0.11
    vitest: 4.0.14
  typescript:
    vue-tsc: 3.1.5
  vue:
    vue: 3.5.25
    vue-router: 4.6.3
