catalogs:
  cloudflare:
    '@nuxthub/core': 0.10.6
    wrangler: 4.68.0
  css:
    tailwindcss: 4.2.0
  icon:
    '@iconify-json/heroicons-solid': 1.2.1
    '@iconify-json/lucide': 1.2.93
  nuxt:
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/ui': 4.4.0
    nuxt: 4.3.1
  test:
    '@nuxt/eslint': 1.15.1
    '@nuxt/eslint-config': 1.15.1
    '@nuxt/test-utils': 4.0.0
    '@vue/test-utils': 2.4.6
    eslint: 9.39.3
    happy-dom: 20.7.0
    vitest: 4.0.18
  typescript:
    vue-tsc: 3.2.5
  vue:
    vue: 3.5.28
    vue-router: 5.0.3
