catalogs:
  cloudflare:
    '@nuxthub/core': 0.10.4
    wrangler: 4.59.1
  css:
    tailwindcss: 4.1.18
  icon:
    '@iconify-json/heroicons-solid': 1.2.1
    '@iconify-json/lucide': 1.2.86
  nuxt:
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/ui': 4.3.0
    nuxt: 4.2.1
  test:
    '@nuxt/eslint': 1.11.0
    '@nuxt/eslint-config': 1.11.0
    '@nuxt/test-utils': 3.23.0
    '@vue/test-utils': 2.4.6
    eslint: 9.39.2
    happy-dom: 20.3.1
    vitest: 4.0.17
  typescript:
    vue-tsc: 3.2.2
  vue:
    vue: 3.5.26
    vue-router: 4.6.4
