allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
catalogs:
  cloudflare:
    '@nuxthub/core': 0.10.7
    wrangler: 4.84.1
  css:
    tailwindcss: 4.2.4
  nuxt:
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/ui': 4.6.1
    nuxt: 4.4.2
  test:
    '@nuxt/eslint': 1.15.2
    '@nuxt/eslint-config': 1.15.2
    '@nuxt/eslint-plugin': 1.15.2
    '@nuxt/test-utils': 4.0.2
    '@stylistic/eslint-plugin': 5.10.0
    '@vue/test-utils': 2.4.6
    happy-dom: 20.9.0
    vitest: 4.1.5
  typescript:
    vue-tsc: 3.2.7
  vp:
    vite: npm:@voidzero-dev/vite-plus-core@0.1.19
    vite-plus: 0.1.19
    vitest: npm:@voidzero-dev/vite-plus-test@0.1.19
  vue:
    vue: 3.5.33
    vue-router: 5.0.6

overrides:
  vite: 'catalog:vp'
  vitest: 'catalog:vp'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
