catalogs:
  cloudflare:
    '@nuxthub/core': 0.9.0
    wrangler: 4.45.0
  css:
    tailwindcss: 4.1.17
  icon:
    '@iconify-json/heroicons-solid': 1.2.1
    '@iconify-json/lucide': 1.2.75
  nuxt:
    '@nuxt/ui': 4.2.1
    nuxt: 4.2.1
  test:
    '@nuxt/eslint': 1.10.0
    '@nuxt/eslint-config': 1.10.0
    '@nuxt/test-utils': 3.20.1
    '@vue/test-utils': 2.4.6
    eslint: 9.38.0
    happy-dom: 20.0.10
    vitest: 4.0.13
  typescript:
    vue-tsc: 3.1.5
  vue:
    vue: 3.5.24
    vue-router: 4.6.3
