catalogs:
  cloudflare:
    '@nuxthub/core': 0.10.7
    wrangler: 4.76.0
  css:
    tailwindcss: 4.2.2
  icon:
    '@iconify-json/heroicons-solid': 1.2.1
    '@iconify-json/lucide': 1.2.98
  nuxt:
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/ui': 4.5.1
    nuxt: 4.4.2
  test:
    '@nuxt/eslint': 1.15.2
    '@nuxt/eslint-config': 1.15.2
    '@nuxt/test-utils': 4.0.0
    '@vue/test-utils': 2.4.6
    happy-dom: 20.8.4
    vitest: 4.1.0
  typescript:
    vue-tsc: 3.2.6
  vue:
    vue: 3.5.30
    vue-router: 5.0.4
  vp:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest
    vite-plus: latest

overrides:
  vite: 'catalog:vp'
  vitest: 'catalog:vp'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
