catalogs:
  cloudflare:
    '@nuxthub/core': 0.10.5
    wrangler: 4.61.0
  css:
    tailwindcss: 4.1.18
  icon:
    '@iconify-json/heroicons-solid': 1.2.1
    '@iconify-json/lucide': 1.2.87
  nuxt:
    '@nuxt/a11y': 1.0.0-alpha.1
    '@nuxt/ui': 4.4.0
    nuxt: 4.3.0
  test:
    '@nuxt/eslint': 1.13.0
    '@nuxt/eslint-config': 1.13.0
    '@nuxt/test-utils': 3.23.0
    '@vue/test-utils': 2.4.6
    eslint: 9.39.2
    happy-dom: 20.4.0
    vitest: 4.0.18
  typescript:
    vue-tsc: 3.2.4
  vue:
    vue: 3.5.27
    vue-router: 5.0.0
