name: Vite+ Format

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "musea/**"
      - "config/**"
      - "README.md"
      - "types/**"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "pnpm-lock.yaml"
      - "vize.config.ts"
      - "vite.config.ts"
      - "tsconfig.json"
      - "tsconfig.vize.json"
      - ".github/workflows/format.yml"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1
        with:
          node-version: "24"
          cache: true
      - name: Install dependencies
        run: vp install
      - name: Run format check
        run: vp run format:check
        env:
          CI: true
